version: '3'
services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD:  password
      TZ: Asia/Tokyo
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spring-app-container
    environment:
      TZ: Asia/Tokyo
      spring.jpa.hibernate.ddl-auto: update
      spring.datasource.url: jdbc:mysql://db/userdb
      spring.datasource.username: admin
      spring.datasource.password: password
    ports:
      - 80:80
    entrypoint: ./scripts/wait-for-it.sh db:3306 -- java -jar app.jar